### ISSUE TITLE
Warn if current version of ROOT or NumPy is different than version built against.

### ISSUE THREAD

**Issue by ndawe** [rootpy/root_numpy#136]
Just a reminder to myself to implement this...

I've had funny results when updating ROOT without recompiling root_numpy.

**Comment by KonstantinSchubert** [comment]
Is this still being worked on?

**Comment by ndawe** [comment]
Still on the to-do list. Did you just hit this issue after updating ROOT?

**Comment by KonstantinSchubert** [comment]
I am having this problem all the time because I keep switching between different versions of ROOT on the same machine. At LHCb, we have setup scripts that load different environments for different tasks.
The same setup script can bring a different version of ROOT today than it did yesterday.

You can force it to use the right version of root  (the one for which root_numpy is built against), but that's hard if I forgot for which version of ROOT root_numpy was built against.

And I forget all the time.

And I am not the only one. I think a lot of people would be happy if this was implemented.

**Comment by ndawe** [comment]
Deal. I think it's high time to have this implemented.

This can't be solely a root_numpy issue though if you have other libraries compiled against ROOT.

**Comment by KonstantinSchubert** [comment]
Thank you :)

> This can't be solely a root_numpy issue though if you have other libraries compiled against ROOT.

The setup scripts take care of most of them, but `root_numpy` is something that we users are installing independently via `pip`.

**Comment by ndawe** [comment]
I now have something working (I think) in #239. Getting close to merging.

**Comment by KonstantinSchubert** [comment]
Cool!

**Comment by ndawe** [comment]
closing via #239
