### ISSUE TITLE
Expose `get_tree_structure`

### ISSUE THREAD

**Issue by kratsg** [rootpy/root_numpy#203]
https://github.com/rootpy/root_numpy/blob/master/root_numpy/src/tree.pyx#L65-L83

I've got code that will want to grab a list of branches for a given `TTree` (well a `TChain`). All current methods require a filename. Probably would be nice to extend the functionality. Perhaps something like updating https://github.com/rootpy/root_numpy/blob/master/root_numpy/_tree.py#L56-L73 to be

```python
def list_branches(*args, **kwargs):
    """Get a list of the branch names of a tree in a ROOT file.
    Parameters
    ----------
    filename : str
        Path to ROOT file.
    treename : str, optional (default=None)
        Name of tree in the ROOT file.
        (optional if the ROOT file has only one tree).
    ==========
    tree : ROOT TTree instance
        The ROOT TTree to list branches of
    Returns
    -------
    branches : list
        List of branch names
    """

    if args[0].Class() in ['TChain', 'TTree']:
        return list(_librootnumpy.get_tree_structure(args[0]))
    elif type(args[0]) is str:
        return _librootnumpy.list_branches(args[0], kwargs.get('treename', None))
```

**Comment by kratsg** [comment]
This might also require exposing `get_tree_structure` perhaps using `cpdef` instead of `cdef`.

**Comment by kratsg** [comment]
Note that there is an equivalent way with just PyROOT:

```
branches = [i.GetName() for i in t.GetListOfBranches()]
```

so I'm not sure if it's a good idea to add this.

**Comment by ndawe** [comment]
Right, ``list_branches`` is really just a convenience function for interactive use (ipython, etc).

On a related note, I would like deprecate ``list_structures`` and implement ``get_structure``. ``list_structures`` currently returns an ordereddict of branch names to lists of (leaf_name, leaf_type). Since it's not a list (it's a dict), I don't think it makes sense to call it ``list_structures``. ``get_structure`` will go beyond that to handle subbranches, and include the leaf shape (akin to numpy's dtype shape) for array branches. Internally, tree2array no longer uses ``list_structures`` to avoid looping over the branches multiple times. This is really just a function to help debugging by providing an easy way to extract the layout of a tree.

**Comment by ndawe** [comment]
Closing for now. Will be deprecating ``list_structures`` (targeting 5.0.0) in favour of a possible future more powerful ``get_structure`` function.
