### ISSUE TITLE
Installation error with gcc4.9?

### ISSUE THREAD

**Issue by qbuat** [rootpy/root_numpy#284]
Hi everyone,

I am having an issue installing root_numpy against `root 6.04.14-x86_64-slc6-gcc49-opt`.

I have the following error message:

``` bash
  /afs/cern.ch/sw/lcg/contrib/gcc/4.9.1/x86_64-slc6/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.9.1/cc1plus: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
  error: command '/afs/cern.ch/sw/lcg/contrib/gcc/4.9.1/x86_64-slc6-gcc48-opt/bin/gcc' failed with exit status 1
```

It works fine with `root 6.04.10-x86_64-slc6-gcc48-opt`

Anyone else noticed this?

Thanks!
Quentin

**Comment by ndawe** [comment]
Looks like a local setup issue. I'll try the same on lxplus now.

**Comment by ndawe** [comment]
I confirm. Strange that the path is /afs/cern.ch/sw/lcg/contrib/gcc/4.9.1/x86_64-slc6-gcc48-opt/bin/gcc instead of /afs/cern.ch/sw/lcg/contrib/gcc/4.9.1/x86_64-slc6-gcc49-opt/bin/gcc  (gcc49 instead of gcc48). And that file is actually present in /afs/cern.ch/sw/lcg/contrib/gcc/4.9.1/x86_64-slc6-gcc49-opt/lib.

**Comment by ndawe** [comment]
It works if you first do this:

```
export LD_LIBRARY_PATH=/afs/cern.ch/sw/lcg/contrib/gcc/4.9.1/x86_64-slc6-gcc49-opt/lib:$LD_LIBRARY_PATH
```

That env on lxplus looks broken to me. Probably worth mentioning to Asoka et al.
